# Site settings
title: Bellt es hinaus
tag_text: Bellt es hinaus
description: Nur mit unserer Hilfe wird VdB Bundespräsident
url: "http://bellteshinaus.at"

# Build settings
markdown: kramdown

exclude: ["README.md"]
